[tools]
elixir = "latest"

[tasks.start_server]
description  = "Start the phoenix dev server in an IEx session"
run = "iex -S mix phx.server"
raw = true

[env]
DISCORD_CLIENT_SECRET = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgY1lXQVNRCnQrOWNRckpVa1QvMFpZR0NPSEZJK1B3dlZZWVc5RGs5L1VBU0tZUXoxdUZzY1pLQzBZUEVYQjR3dnF6THdMUHUKbU9rOFRYN0NXanNoN2Z0dVB0TmlBdXBRR2dzb1hqMElHRTJnSFBVZkI4dGJMQ20xQXRZbnc5WkJoWDFuZVVrbApIdlo0M1o3Q2lLZnBkQkJwaGk4TU1VSkE0d3gwMnJqZDNJcURWYWdMdXRndkV2UFBVNkZSYjZqMk80eEZRV1RBCmpNWmpONGVJZjFGS0wreHF2UHVQcEFsQ2Fhb0ZreERGdnhOVnRQcGdtbWVWYWErRnhzcUE0S1FOZ0ZDdGZ2SXQKc1VabWdCVGQzL0M5R3ZyY1JwQ2E0b3QyNVN5SWQvK0UzaGVSM2xGaHRMME1ybDFlSlBvZzlyUEV1SklmUVhjWQpOQm1ueXZ6NnYrSlNnMmMzNmZhb3VMemRNZjB4d2VBTlBBbVFmNFdmdStIc28vOXExd2NBaU5Qa2JaVU1vUzY2CkhuNTF0d2hMSU5QeFBDMTNuUFk4bzNiTmJBVkowNDdiOFpMS05HMXhWNDdhNm12bXdhSkNia2lYdXpqNXRSbzgKbDJob0k5NFlVZnJTc0FUd3k0L0lGYmM4WW1Db0Y2MUNMR3ljNENDR1Z2cUZGWUVITkJvN0orV1I4NHBjSVY4bQoKLT4ga0d+LWdyZWFzZSB5PVsKN09qK1ZxdjdNSmp1UVdaUml4U0FrZwotLS0gWjA3UWpRSGZtNXZwOGw5QWZReGFQcTRmWW9TTzhKL3VWUko3UmthZERmOApmGDR4a+kKvHwyoG4XaquECDYny7ntZi7luECNCb44ysUm97L6cIJimTfkoSG6dR8H8Qo1fdmvkTr1Idlx8RRe" }
DISCORD_CLIENT_ID = "1454935634434199758"
